spring:
  jpa:
    generate-ddl: true
    show-sql: true
    database: h2
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: kata
    password: kata
    driverClassName: org.h2.Driver
    initialization-mode: always